#!/bin/zsh

## TERMINATE ALL
./terminate4

BUILD_IDENTIFIER=MythosTeam.Mythos

## CLEAN
# BUILD_DIR=`find /Users/luizsena/Library/Developer/Xcode/DerivedData/POC-websocketClientSide-*/ -print | head -n 1`
# if [ -d "$BUILD_DIR" ]; then
#     echo Cleaning $BUILD_DIR;
#     rm -rf $BUILD_DIR;
# else
#     echo "Clean not needed";
# fi

## BUILD
#xcodebuild -project POC-websocketClientSide.xcodeproj -scheme POC-websocketClientSide -destination 'platform=iOS Simulator,name=iPhone 12 A 16.4,OS=16.4'

APPBUILD=`find /Users/narelylima/Library/Developer/Xcode/DerivedData/Mythos-*/Build/Products/Debug-iphonesimulator -type d -name "Mythos.app" -print | head -n 1`
echo $APPBUILD

## OPEN SIMULATORS
IPHONE12_A_16=6A6CB0CE-524D-4BA2-A734-8DE5F9FE7B01
IPHONE12_B_16=3F643426-211B-42DE-8F53-2105F0F59D8E
IPHONE12_A_16_4=A62C1104-155F-44F4-ACCD-E7BBC244DBF9
IPHONE12_B_16_4=1BF0E6378-A871-4352-885E-D312089FB9A9

echo "Start simulators"

echo $APPBUILD
echo $BUILD_IDENTIFIER
echo $IPHONE12_A_16

/Users/narelylima/Documents/iOS/Final-challenge/Mythos/build1 $APPBUILD $BUILD_IDENTIFIER $IPHONE12_A_16 &
/Users/narelylima/Documents/iOS/Final-challenge/Mythos/build1 $APPBUILD $BUILD_IDENTIFIER $IPHONE12_B_16 &
/Users/narelylima/Documents/iOS/Final-challenge/Mythos/build1 $APPBUILD $BUILD_IDENTIFIER $IPHONE12_A_16_4
# ./build1 $APPBUILD $BUILD_IDENTIFIER $IPHONE12_B_16_4
