#!/bin/zsh

## TERMINATE ALL
./terminate4

BUILD_IDENTIFIER=MythosTeam.Mythos

## CLEAN
# BUILD_DIR=`find /Users/luizsena/Library/Developer/Xcode/DerivedData/POC-websocketClientSide-*/ -print | head -n 1`
# if [ -d "$BUILD_DIR" ]; then
#     echo Cleaning $BUILD_DIR;
#     rm -rf $BUILD_DIR;
# else
#     echo "Clean not needed";
# fi

## BUILD
#xcodebuild -project POC-websocketClientSide.xcodeproj -scheme POC-websocketClientSide -destination 'platform=iOS Simulator,name=iPhone 12 A 16.4,OS=16.4'

APPBUILD=`find /Users/ciceronascimento/Library/Developer/Xcode/DerivedData/Mythos-*/Build/Products/Debug-iphonesimulator -type d -name "Mythos.app" -print | head -n 1`
echo $APPBUILD

## OPEN SIMULATORS
IPHONE12_A_16=7117430B-9BA1-4BBD-B452-C1C3D00DB6CA
IPHONE12_B_16=547DB4F7-CE79-43C3-ACED-4294AB5377D0
IPHONE12_A_16_4=5BF0C18D-4FA8-4812-BB05-52B26E749B70
IPHONE12_B_16_4=1ED92328-709B-48B4-A4D1-AD9C0E32DE3E

echo "Start simulators"

echo $APPBUILD
echo $BUILD_IDENTIFIER
echo $IPHONE12_A_16

/Users/ciceronascimento/Documents/ADA/Final-challenge/Mythos/build1 $APPBUILD $BUILD_IDENTIFIER $IPHONE12_A_16 &
/Users/ciceronascimento/Documents/ADA/Final-challenge/Mythos/build1 $APPBUILD $BUILD_IDENTIFIER $IPHONE12_B_16 &
/Users/ciceronascimento/Documents/ADA/Final-challenge/Mythos/build1 $APPBUILD $BUILD_IDENTIFIER $IPHONE12_A_16_4
# ./build1 $APPBUILD $BUILD_IDENTIFIER $IPHONE12_B_16_4
